version: "2"

services:

  hz1:
    image: imap-node-1
    container_name: imap-node-1
    hostname: imap-node-1
    ports:
      - 18080:8080/tcp
    networks:
      nw1:
        ipv4_address: 172.16.238.11
      nw2:
        ipv4_address: 172.16.239.11
    entrypoint: java -cp "resources:lib/*" io.github.mxns.lab.hazelcast.Main 172.16.238.11

  hz2:
    image: imap-node-2
    container_name: imap-node-2
    hostname: imap-node-2
    ports:
      - 28080:8080/tcp
    networks:
      nw1:
        ipv4_address: 172.16.238.12
      nw2:
        ipv4_address: 172.16.239.12
    entrypoint: java -cp "resources:lib/*" io.github.mxns.lab.hazelcast.Main 172.16.238.12

networks:
  nw1:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
  nw2:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
        gateway: 172.16.239.1
